name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install poetry
        run: pip install poetry poetry-core
        shell: bash
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
          check-latest: true
      - name: Install dependencies
        run: |
          poetry install --no-root
        shell: bash
      - name: Build and Publish
        run: |
          poetry config repositories.publish https://upload.pypi.org/legacy/
          poetry publish -p ${{ secrets.PYPI_TOKEN }} -u __token__ -r publish --build
        shell: bash
