name: Build and publish python package

# Only run on new tags
# on:
#   release:
#     types: [ published ]
# Run on any push to master
on:
  push:
    branches:
      - master

jobs:
  publish-service-client-package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install poetry
        run: pip install poetry poetry-core
        shell: bash
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
          check-latest: true
      - name: Install dependencies
        run: |
          poetry install --no-root
        shell: bash
      - name: Build and Publish
        run: |
          poetry publish --build -n -p ${{ secrets.PYPI_TOKEN }} -u __token__  -vvv
        shell: bash
